const enum ResponseCode {
    EPTR_AUTOMATICAL = 'EPTR_AUTOMATICAL',
    EPTR_BATTERY_LOW = 'EPTR_BATTERY_LOW',
    EPTR_COVER_OPEN = 'EPTR_COVER_OPEN',
    EPTR_CUTTER = 'EPTR_CUTTER',
    EPTR_MECHANICAL = 'EPTR_MECHANICAL',
    EPTR_REC_EMPTY = 'EPTR_REC_EMPTY',
    EPTR_UNRECOVERABLE = 'EPTR_UNRECOVERABLE',
    SchemaError = 'SchemaError',
    DeviceNotFound = 'DeviceNotFound',
    PrintSystemError = 'PrintSystemError',
    EX_BADPORT = 'EX_BADPORT',
    EX_TIMEOUT = 'EX_TIMEOUT',
    EX_SPOOLER = 'EX_SPOOLER',
    JobNotFound = 'JobNotFound',
    Printing = 'Printing',
    JobSpooling = 'JobSpooling',
    TooManyRequests = 'TooManyRequests',
    RequestEntityTooLarge = 'RequestEntityTooLarge',
    ERROR_WAIT_EJECT = 'ERROR_WAIT_EJECT',
}